### ISSUE TITLE
[Bug] You are not in administrator mode!

### ISSUE THREAD

**Issue by graysuit** [gammasoft71/xtd#1]
![Capture](https://user-images.githubusercontent.com/54432616/103894148-4ee6b080-5110-11eb-8dca-9ffc41bc862e.PNG)

This says You are not **admin** even I am running an admin command prompt. 

I guess net session isnt correct way to detect whether cmd is admin.
```cmd
C:\Program Files\Microsoft Visual Studio\2017\Community>net session
The Server service is not started.

More help is available by typing NET HELPMSG 2114.
```
Reason : [here](https://superuser.com/questions/667607/check-if-current-command-prompt-was-launched-as-the-administrator#comment1658584_667745)
This is **incorrect** way:
```cmd
:: check if administrator mode
net session > nul 2>&1
IF %ERRORLEVEL% neq 0 (
  echo You are not in administrator mode!
  echo Run cmd as administrator before execute install.
  exit /B 1
)
```

**Comment by gammasoft71** [comment]
Unfortunately, there is not really a good solution to remedy the problem. 

So I replaced the wrong code by this:

:: check if administrator mode
fsutil dirty query %systemdrive% > nul 2>&1
IF %ERRORLEVEL% neq 0 (
  echo You are not in administrator mode!
  echo Run cmd as administrator before execute install.
  exit /B 1
)

Hopefully this will fix the problem for everyone.

(see https://stackoverflow.com/questions/4051883/batch-script-how-to-check-for-admin-rights#11995662)

**Comment by graysuit** [comment]
This depend on Asp.net Server service to be started to detect admin. If it doesn't running then it will result in error.
And error can be anything. Hence script treat that error as non-admin issue.
So its not recommend even majority uses it.
 ```batch
 rem^ &cscript //nologo //e:vbscript "%~f0"

Rem run cmd commnds here
rem^ &echo hello
Rem run cmd commnds here

rem^ &exit /B 1


'----- VBS portion ------------
If Not WScript.Arguments.Named.Exists("elevate") Then
    Msgbox "You are NOT admin"  
Else
    Msgbox "You are admin"
End If
 ```
 You can also use runas.exe to ask for admin rights like [here](https://github.com/NYAN-x-CAT/Bypass-Windows-Defender-VBS/blob/master/script.vbs#L9-L13).
Nevermind, don't take this issue serious. Its just minor bug. ;)
