### ISSUE TITLE
[BUG] can not build

### ISSUE THREAD

**Issue by kkptm** [gammasoft71/xtd#182]
CMake Error at build/cmake/functions.cmake:596 (add_library):
  Cannot find source file:

    D:/xtd-master/build/3rdparty/wxWidgets/src/jpeg/jaricom.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  build/cmake/lib/jpeg.cmake:11 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  Cannot find source file:

    D:/xtd-master/build/3rdparty/wxWidgets/src/png/png.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  build/cmake/lib/png.cmake:21 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  Cannot find source file:

    D:/xtd-master/build/3rdparty/wxWidgets/src/tiff/libtiff/tif_win32.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  build/cmake/lib/tiff.cmake:19 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxregex
Call Stack (most recent call first):
  build/cmake/lib/regex.cmake:13 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxzlib
Call Stack (most recent call first):
  build/cmake/lib/zlib.cmake:13 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxexpat
Call Stack (most recent call first):
  build/cmake/lib/expat.cmake:13 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxjpeg
Call Stack (most recent call first):
  build/cmake/lib/jpeg.cmake:11 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxpng
Call Stack (most recent call first):
  build/cmake/lib/png.cmake:21 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Error at build/cmake/functions.cmake:596 (add_library):
  No SOURCES given to target: wxtiff
Call Stack (most recent call first):
  build/cmake/lib/tiff.cmake:19 (wx_add_builtin_library)
  build/cmake/lib/CMakeLists.txt:28 (include)

CMake Generate step failed.  Build files cannot be regenerated correctly.
Installing xtd...
子目录或文件 build 已经存在。
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.19044.
CMake Warning at scripts/cmake/xtd_commands.cmake:2167 (message):
  Doxygen not found try with set "XTD_DOWNLOAD_DOXYGEN" option to ON
Call Stack (most recent call first):
  CMakeLists.txt:54 (include)

CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.23/Modules/FindwxWidgets.cmake:1025 (find_package_handle_standard_args)
  src/xtd.drawing.native.wxwidgets/CMakeLists.txt:18 (find_package)

**Comment by gammasoft71** [comment]
The issue was closed by you.
Did the build finally work?

**Comment by kkptm** [comment]
no,the problem is with clone wxwidgets

**Comment by gammasoft71** [comment]
Do you use the xtd installation or do you do a manual installation?

If you install manually after cloning wxWidgets you have to execute the following line to install submodules in the wxWidgets root folder:

```shell
git submodule update --init 
```

**Comment by kkptm** [comment]
i used use the xtd install.cmd

**Comment by gammasoft71** [comment]
Are you on version 0.1.0 or on the trunk?

Can you delete the xtd/build folder. And restart the install.
Then send me the output of the installation.

**Comment by gammasoft71** [comment]
No enough information --> closed.
