### ISSUE TITLE
[BUG] xtd.tunit - Invalid links in xtd/examples/xtd.tunit.examples/README.md

### ISSUE THREAD

**Issue by jimorc** [gammasoft71/xtd#183]
# Describe the bug

All links in xtd/examples/txd.tunit.examples/README.md to header files produce 404 error

# To Reproduce

1. On Github, open gamasoft71/xtd/examples.xtd.tunit.examples//README.md
2. Click on any of the links that begin with xtd::unit::
3. Web page showing Github 404 error page is displayed.

# Expected behaviour

Display appropriate header file

# Screenshots

None

# Desktop (please complete the following information)

N/A

I will generate a pull request to fix this if this issue is accepted.

**Comment by gammasoft71** [comment]
Thank you for your return.

Your pool request is welcome ;-)

**Comment by gammasoft71** [comment]
Indeed, there are many markdown files with many links.

The xtd::tunit::line_info class and the line_info_ keyword have been replaced by the xtd::diagnostics::stack_frame class and the csf_ (or current_stack_frame_) keyword.

If you think it's too ambitious for you, I can take care of it. 

Or if you can't figure out how to correct or fix the links you can ask me.

You can also do it in small pieces to make it easier.

Don't hesitate to come back to me ;-)

**Comment by gammasoft71** [comment]
It seems to me that for most of the links, it is enough to replace
the path `https://github.com/gammasoft71/xtd/blob/master/src/xtd.tunit/include/xtd/xxx.h`
by `https://github.com/gammasoft71/xtd/blob/master/src/xtd.tunit/include/xtd/tunit/xxx.h`

`xxx` being the class name of the link.

And then see after the particular cases like `line_info_` and others...

**Comment by jimorc** [comment]
Adding tunit/ to the path is what I have been doing.

I only mentioned the necessary changes to document what is needed. Otherwise, this issue would imply that changes to a single markdown file would be sufficient to complete this issue. This would be a mismatch to the many files changed in the pull request. I am working on it.

**Comment by gammasoft71** [comment]
The markdown file hierarchy is important. I use this hierarchy to document the examples in xtdc-gui (not finished yet).
But my goal is to generate html pages to document the examples through control xtd::forms::web_browser (not yet written).
The goal is to present the examples a bit like in Qt Creator.

Therefore the classification into subgroups with redundant information on the brief information is necessary.
The files of the subfolders give only a brief description of the different examples that compose it. 
While each example contains (will contain) a detailed description of the example.

This may seem very redundant at the moment, as the detailed description of an example is not yet written.
But this will come with time.

Moreover the advantage is to have a README.md in each directory to describe the content of the directory when you browse it via github.
Most of the directories in xtd have a README.md.

# Summary

## xtd/examples/README.md

Exemple
  * xtd.core.examples
    * Hello Worlds [Brief description of examples group]
    * ...
  * xtd.Forms
    * ...
  * xtd.tunit
    * ...
  * ...

## xtd/examples/xtd.core.examples/README.md

xtd.core
  * Hello World  [Brief description of example]
  * ...    

## xtd/examples/xtd.core.examples/hello_wolrds/README.md

  * hello_world_console  [Brief description of example (the same as parent)]
  * ...  

## xtd/examples/xtd.core.examples/hello_wolrds/hello_worlds/hello_world_console/README.md

Provides a brief and detailed description for hello Wordl console

**Comment by jimorc** [comment]
I was not questioning why you set up the document structure you did, just documenting all of the changes that are required.

**Comment by gammasoft71** [comment]
Yes but the purpose of my remark is precisely so that you understand why some pages could seem redundant ;-)

**Comment by jimorc** [comment]
I have done a pull request. It seems to have created issue 184.

**Comment by gammasoft71** [comment]
The number #184 is the number of the pull request ;-)
I will set fixed attribute and close the issue #183.

**Comment by gammasoft71** [comment]
I have reviewed your contribution and everything seems correct. 
Thank you
