### ISSUE TITLE
[BUG] xtd::forms - Adding collapsible_panel::parent call results in very minimal main window

### ISSUE THREAD

**Issue by jimorc** [gammasoft71/xtd#189]
# Describe the bug

Calling collapsible_panel::parent to attach to a form or panel causes the program to start with a minimal title bar and nothing else. See the screenshot below.

# To Reproduce

1. Build and execute the sample program collapsible_panel.cpp. Program opens with display as shown in screenshot.
2.  Comment out the lines
```
    collapsible_panel2.parent(*this);
...
    collapsible_panel1.parent(*this);
```
3. Build and execute. Program opens with form1 client area visible.

# Expected behaviour

Program should open with form1 client area visible and containing the collapsible panels.

# Screenshots

<img width="152" alt="Screen Shot 2022-08-21 at 11 03 11" src="https://user-images.githubusercontent.com/4800120/185798455-1ef431ff-bf41-4240-9465-6d9de5d4e818.png">

# Desktop (please complete the following information)

 - OS: MacOS
 - Version: 12.5.1
- xtd version: from master a few days ago

**Additional context**

N/A

**Workaround**

None known

**Comment by gammasoft71** [comment]
The development of the collapsible_panel control is not yet finished.
There is a draft at the moment which is far from being satisfactory.
It is planned for version 0.2.0.

For more information see the [roadmap](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md) and the related [issue #60](https://github.com/gammasoft71/xtd/issues/60).

Duplicate [#60](https://github.com/gammasoft71/xtd/issues/60).
