### ISSUE TITLE
[ENHANCEMENT] xtd.forms - xtd::forms::combo_box - added drop_down and drop_down_closed events

### ISSUE THREAD

**Issue by jimorc** [gammasoft71/xtd#190]
# Your question

I have a combo_box with drop_down_list style. Is there an event that is triggered when the dropdown list is opened?

I could only find one event: selected_index_changed. If a drop_down_list_opened event does not exist at this time, is it planned for the future?

**Comment by jimorc** [comment]
Actually, the event would be better named drop_down_list_opening. I want to populate the list in real time.

**Comment by gammasoft71** [comment]
Two events will be added for the release 0.2.0 :

* drop_down : Occurs when the drop-down portion of a xtd::forms::combo_box is shown.
* drop_down_close : Occurs when the drop-down portion of the xtd::forms::combo_box is no longer visible.

**Comment by gammasoft71** [comment]
Fixed in commit [e794949](https://github.com/gammasoft71/xtd/commit/e7949492a7babe46ff9c74c54030c9665ef83928)
