### ISSUE TITLE
[BUG] xtd.forms - form::show_dialog called within main() has wait cursor

### ISSUE THREAD

**Issue by jimorc** [gammasoft71/xtd#196]
# Describe the bug
Wait cursor is displayed on any form that is displayed as a modal dialog before application::run is called.
See the program below:
```
#include <xtd/xtd>

using namespace xtd;
using namespace xtd::forms;

class dialog : public form
{
    public:
        dialog() {}
};

class form1 : public form
{
    public:
        form1()
        {
            show_button.text("Show Dialog");
            show_button.anchor(anchor_styles::left | anchor_styles::top | anchor_styles::right);
            show_button.click += [&] () { show_it(); };

            *this << show_button;
        }
        void show_it()
        {
            dialog d; 
            d.show_dialog();
        }
    private:
        button show_button;
};
int main()
{
    dialog d;
    d.show_dialog();
    form1 f;
    f.show_dialog();
    application::run(f);
    return EXIT_SUCCESS;
}
```

# To Reproduce

1. Build and execute the program above.
1. Note that when the dialog is displayed via show_dialog() call, and the cursor is moved over the client area of the dialog, the cursor changes to the wait cursor. 
1. Close the dialog. form1 is now displayed as a dialog. Again the wait cursor is set. 
1. Close the form1. Now application::run is called with form1 as argument. The arrow cursor is set.
1. Click on the button. A dialog object is created and displayed using show_dialog(). This time the arrow cursor is used.

# Expected behaviour

The arrow cursor show be displayed always.

# Screenshots

N/A

# Desktop (please complete the following information)

 - OS: MacOS
 - Version: 12.5.1
- xtd version: built from master after fixes for issues 192, 193, 194.

**Additional context**

N/A

**Workaround**

None. Functionality still works.

**Comment by gammasoft71** [comment]
After some thought, there is a very simple solution to this problem. 
Just set the default height value to 21 and not 26.
The default height will then be :
* 34 for Gnome, 
* 23 for Windows
* 21 for macOS and not 26.
