### ISSUE TITLE
[BUG] Installing xtd in Arch Linux

### ISSUE THREAD

**Issue by KaimDev** [gammasoft71/xtd#199]
# Problem installing xtd on Arch Linux

**Terminal log attached.**
https://sharetext.me/2hcsszrenb

# Desktop

 - OS: [Arch Linux]
- xtd version: latest version

**Comment by gammasoft71** [comment]
There are warnings with gcc 12. By default the xtd build treats warnings as errors.

I will install a toolchain with gcc 12 to check and correct the problem.

# WORKAROUND

In the meantime you could set the parameter: XTD_SET_COMPILER_OPTION_WARNINGS_AS_ERRORS to OFF.

```bash
rm -rf ./build
./install -DXTD_SET_COMPILER_OPTION_WARNINGS_AS_ERRORS=OFF
```

**Comment by gammasoft71** [comment]
## Remarks

Before rerunning the installation, delete the build folder :

```bash
rm -rf ./build
```

**Comment by gammasoft71** [comment]
I installed a tool chain with gcc 12 and fixed the problem.
