### ISSUE TITLE
[ENHANCEMENT] xtd.forms - text_box::placeholder_text()

### ISSUE THREAD

**Issue by baderouaich** [gammasoft71/xtd#206]
# Hint text
I'd like to see xtd::text_box::hint() (also known as placeholder), sometimes it can be a good alternative for labels, or it can describe the format of the desired input...

# Describe the solution you'd like
wxWigets's [wxTextControl ](https://docs.wxwidgets.org/3.0/classwx_text_entry.html) has SetHint() to achieve such thing.

# Additional context
![image](https://user-images.githubusercontent.com/49657842/203855804-8b5aab14-7a67-4c12-b8c5-bb7d306c304d.png)
![image](https://user-images.githubusercontent.com/49657842/203855317-094747f4-0bc3-4420-bcff-dcbbe28b0145.png)

**Comment by gammasoft71** [comment]
Hello again, 

this is a thought transmission lol.  While modifying your ´xtd_dev_tool' project earlier, I was just thinking that the placeholder was missing to be able to display ´enum string here…´.  I will therefore add it to the long list of what there is to do.  

If you have the time and the inclination you can add it.  It’s easy :
* new property ´xtd::forms::text_box::placeholder_text’…

**Comment by baderouaich** [comment]
LOL! 🤣 i had the same thought when i tired the changes you added, i saw the "Enum string here..." as value and i had to remove it then paste other text, it will be nice to have placeholder text instead.
I would like to add the `xtd::forms::text_box::placeholder_text` by tomorrow 😄👍
