### ISSUE TITLE
[BUG] xtd.forms - assertion failed on debug mode

### ISSUE THREAD

**Issue by baderouaich** [gammasoft71/xtd#207]
# Describe the bug
If i run an xtd forms application in debug mode i get an exception box with the bellow debug message: 
```txt
wxAssert
--------
cond="paintStack.top().window == window", msg=wxPaintDC must be associated with the window being repainted
  at wxPaintDCImpl::wxPaintDCImpl in C:\Users\bader\Dev\xtd\build\3rdparty\wxWidgets\src\msw\dcclient.cpp:line 262
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message----

---- Assert Long Message----

   at xtd_assert_handler in C:\Users\bader\Dev\xtd\src\xtd.drawing.native.wxwidgets\src\xtd\drawing\native\wxwidgets\toolkit.cpp:line:36
```

# To Reproduce

1. Clone and install xtd with latest updates
2. Create new xtd forms gui project 
3. Try build and run in Debug mode
4. See exception box error

# Screenshots.
![image](https://user-images.githubusercontent.com/49657842/204606083-dc7fe100-81e3-421c-81f7-1ea074f80274.png)
![image](https://user-images.githubusercontent.com/49657842/204603828-a9908ac5-5deb-4ac1-98c0-b6c0f5305930.png)

# Desktop (please complete the following information)

 - OS: Windows
 - Version: 10 21H2
 - xtd version: 0.2.0 (recent [commit ](https://github.com/gammasoft71/xtd/commit/4f1045d64c5ff9ab07b0eb4e8389e4cc5752c6a7) from master branch)

**Workaround**

This occurs only in Debug mode, Release works fine.

**Comment by gammasoft71** [comment]
I look at it as soon as possible

**Comment by gammasoft71** [comment]
Fixed in https://github.com/gammasoft71/xtd/commit/56dfd1f98b22133ce11e7441e9bee775d5e90ffe
