### ISSUE TITLE
Tabs control

### ISSUE THREAD

**Issue by TheHellTower** [gammasoft71/xtd#213]
# Your question

Hello I wanted to search in the documentation how to actually create a tab control and add elements to it but I found nothing, could you guide me ?

Regards.

**Comment by gammasoft71** [comment]
Hello,

* You can following this minimal [containers](https://github.com/gammasoft71/xtd/blob/master/docs/containers.md#tab-control)  guide (more guide will follow later).
* You can see [tab_control](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1tab__control.html) and [tab_pages](https://codedocs.xyz/gammasoft71/xtd/classxtd_1_1forms_1_1tab__page.html) int the Reference Guide.
* You can see [tab_control](https://github.com/gammasoft71/xtd/blob/master/examples/xtd.forms.examples/containers/tab_control/README.md) and [colored_tab_pages]() examples.
* There are other [examples](https://github.com/gammasoft71/xtd/blob/master/examples/xtd.forms.examples/README.md) that use the tab_control and tab_page containers..

Regards,
Gammasoft71

**Comment by TheHellTower** [comment]
Thank you it work perfectly, hopefully you will or have a good day/night.

Regards.
