### ISSUE TITLE
[ENHANCEMENT] Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [gammasoft71/xtd#214]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
- [hdc_wrapper](https://github.com/gammasoft71/xtd/blob/c1b2e180eb223d372de72bb4a2a28c1e6f7ffd31/src/xtd.drawing.native.wxwidgets/include/xtd/drawing/native/hdc_wrapper.h#L21 "Destructor for hdc_wrapper")
- [paint_event_args](https://github.com/gammasoft71/xtd/blob/0797e8ce6477463d66f7f80583cb6bc988754c0b/src/xtd.forms/src/xtd/forms/paint_event_args.cpp#L17 "Destructor for paint_event_args")
- [StackWalker](https://github.com/gammasoft71/xtd/blob/a93f34a4c4e0a652b6c82392d984d8341357833b/src/xtd.3rdparty.call_stack/stack_walker.cpp#L708 "Destructor for StackWalker")

**Comment by gammasoft71** [comment]
Thank you for your interest in xtd and for your feedback.

Indeed, there are indeed too many nullptr tests.

How did you find these redundant tests? With a tool or by simply reading the code?

xtd is regularly scanned with cppcheck and this error is not highlighted.

Kind regards

Gammasoft

**Comment by elfring** [comment]
>With a tool

[Yes](https://docs.github.com/en/search-github/searching-on-github/searching-code "Source code search").


>or by simply reading the code?

Partly, yes.


>… and this error is not highlighted.

:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/readability/delete-null-pointer.html "Deletion of unnecessary null pointer checks")?

**Comment by elfring** [comment]
[Further update candidates were left over](https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.3rdparty.call_stack/stack_walker.cpp#L211 "Update candidate: Destructor for StackWalkerInternal").

**Comment by elfring** [comment]
Thanks for your small source code improvements.
*  [A](https://github.com/gammasoft71/xtd/commit/80d3ab8395b64406731a545aed4ff0b198550818 "Removal of redundant checks before delete")
* [B](https://github.com/gammasoft71/xtd/commit/3f4909c01510ad738f0be4d1a7624e8199caece1 "Removal of redundant checks before free()")

:crystal_ball: Would you become interested to perform similar adjustments in any more software areas?

**Comment by gammasoft71** [comment]
Why not 😉

**Comment by elfring** [comment]
[Another update candidate was left over](https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.drawing.native.wxwidgets/include/xtd/drawing/native/hdc_wrapper.h#L42 "Update candidate: hdc_wrapper::create()").

:crystal_ball: Would you like to help with [improving a semantic patch language (Coccinelle software)](https://coccinelle.gitlabpages.inria.fr/website/ "Source code matching and transformation") accordingly?
