### ISSUE TITLE
[BUG] Do not use “localhost” in public links

### ISSUE THREAD

**Issue by elfring** [gammasoft71/xtd#215]
:thought_balloon: I suggest to [replace the specification “localhost:3000”](https://github.com/gammasoft71/xtd/commit/8115aa48447d4bcc947a96238806e03d179f1bc7#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L11 "Update candidate") by an address which is more desirable for the use in public documents.

**Comment by elfring** [comment]
Thanks for [your address correction](https://github.com/gammasoft71/xtd/commit/3f4d4f379d801f468cec546cca8911a5ed70ab57 "Update for links").

**Comment by gammasoft71** [comment]
Thank you for your feedback.
