### ISSUE TITLE
[ENHANCEMENT] Reduce duplicate condition checks

### ISSUE THREAD

**Issue by elfring** [gammasoft71/xtd#217]
:eyes: I noticed that the member variable “stream_” was checked twice at a few source code places.

Examples:
* [Destructor for the class “binary_writer”](https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.core/src/xtd/io/binary_writer.cpp#L27 "Update candidate")
* [Destructor for the class “stream_writer”](https://github.com/gammasoft71/xtd/blob/26e93bb8e656974e347ea84abba4917b0eb8444e/src/xtd.core/src/xtd/io/stream_writer.cpp#L34 "Another update candidate")

:crystal_ball: How many implementation details can be improved accordingly?

**Comment by gammasoft71** [comment]
Do not rely on a static analysis tool with your eyes closed. You know that there are often false positives.
Indeed, you have to analyze the code to make sure that the static analysis tool does not detect a false positive. 

Throwing a correction proposal without having checked the veracity of the error provided by the static analysis tool can only waste everyone's time.
When a simple reading of the code would have been enough to see that there is no error. 
Moreover the pointed classes are small and self containing. 
Analyse the code and see by yourself that there is no error 😉.

**Comment by elfring** [comment]
:thinking: I imagine that a bit of source code can be optimised like the following.

```diff
 stream_writer::~stream_writer() {
   if (delete_when_destroy_ && stream_) {
     flush();
-    if (stream_ && dynamic_cast<ofstream*>(stream_)) static_cast<ofstream*>(stream_)->close();
+    if (dynamic_cast<ofstream*>(stream_)) static_cast<ofstream*>(stream_)->close();
     delete stream_;
   }
 }
```


:thought_balloon: Can repeated checks be avoided at any more places (within compound statements)?

**Comment by gammasoft71** [comment]
Ok, I agree with you. 
But why don't you make a [pull request](https://github.com/gammasoft71/xtd/pulls) ?
There would be no ambiguity about the correction and there would be much less back and forth between you and me --> time saving.

**Comment by elfring** [comment]
>Ok, I agree with you.

Thanks for such a positive feedback.


>But why don't you make a pull request?

* The applied MIT licence influences contribution considerations.
* I became curious if it would be needed to detect similar update candidates in systematic ways.

**Comment by gammasoft71** [comment]
>The applied MIT licence influences contribution considerations.

So what's wrong with the MIT license for your pull request? It is one of the most open licenses available.

> I became curious if it would be needed to detect similar update candidates in systematic ways.

The fact of using a pull request does not prevent the questioning. A pull request is reviewed by definition 😉

**Comment by elfring** [comment]
>So what's wrong with the MIT license …?

:thinking: I find licence variants with a copyleft more appealing.

**Comment by gammasoft71** [comment]
> 🤔 I find licence variants with a copyleft more appealing.

So stop bothering with projects whose licenses don't fit you 😅
Instead, find projects that fit you 100% or create your own c++ project 😉.

**Comment by elfring** [comment]
I got into the mood often enough to point remaining improvement possibilities out.
