### ISSUE TITLE
[BUG] xtd::forms - Arguments get split up after doing application::restart

### ISSUE THREAD

**Issue by FoofooTheGuy** [gammasoft71/xtd#222]
# Description

After doing xtd::forms::application::restart, the arguments passed when first starting the application get split if there was a space in the text.

# To Reproduce

I took the application_restart example and added an argument parser to show the bug
```cpp
#include <xtd/xtd>
#include <vector>

using namespace std;
using namespace xtd;
using namespace xtd::forms;

int main() {
  auto restart_count = 0;
  if (!environment::get_environment_variable("applicatioon_restart_count").empty())
    restart_count = parse<int>(environment::get_environment_variable("applicatioon_restart_count"));

  auto main_form = control::create<form>(ustring::format("Restart {} times", restart_count));
  auto restart_button = control::create<button>(*main_form, "Restart", {10 ,10});
  restart_button->click += application::restart;

  //parse args
  std::vector<ustring> argv = environment::get_command_line_args();
  for (auto& arg : argv) {
      message_box::show(*main_form, arg, "Test", xtd::forms::message_box_buttons::ok, xtd::forms::message_box_icon::warning);
  }

  environment::set_environment_variable("applicatioon_restart_count", to_string(restart_count + 1));

  application::run(*main_form);
}
```

# Expected behaviour

It should parse the arguments the same way that it does it the first time the program runs (see images)

# Screenshots

Say I run the program with this argument: `application_restart.exe "file with spaces.bin"`

The first time it runs: (expected, normal)
![image](https://user-images.githubusercontent.com/32585652/225422959-c05d6d14-52f0-4f02-91d0-fd2e08f499e6.png)

The way it runs after the restart: (unexpected, broken)
![image](https://user-images.githubusercontent.com/32585652/225423029-69ddd979-4e93-422c-999c-2e4f7d4478b1.png)

# Desktop

- OS: Windows
- Version: 8.1 (But I would assume this also happens on others)
- xtd version: 0.1.0

# Work-around?/What do to fix it I guess

I don't know if this issue is already known and to be honest I didn't do much checking to see if this issue was already reported, but I actually can't imagine any way to fix it without changing something in xtd itself. I kind of thought about using the number of args to fix it but that actually won't work so it is probably only fixable by changing the way it passes the args to itself when restarting.

**Comment by gammasoft71** [comment]
Thanks for the issue feedback.

Indeed, the problem must come from the class [xtd::forms::application](https://gammasoft71.github.io/xtd/reference_guides/latest/classxtd_1_1forms_1_1application.html).
I'll look at it as soon as possible.

**Comment by gammasoft71** [comment]
I fixed it in commit [63fb4db](https://github.com/gammasoft71/xtd/commit/63fb4db28bd9cafb9f9b8c1046e99e14daf8405c)
Can you try if it is correct for you?

**Comment by FoofooTheGuy** [comment]
Sorry, I just saw your message. From just looking at the code I think it should do the trick, but I'll download and install it right now to be sure

**Comment by FoofooTheGuy** [comment]
Okay, it works properly now

**Comment by gammasoft71** [comment]
Thank’s
