### ISSUE TITLE
[BUG] Build failed with XTD_BUILD_LIBRARIES_XTD_DRAWING=OFF

### ISSUE THREAD

**Issue by ex-purple** [gammasoft71/xtd#225]
# Describe the bug

Currently, the XTD_BUILD_LIBRARIES_XTD_DRAWING option must always be enabled for a successful build. Otherwise, the project is not built:
`include/xtd/system_report.h:10:10: fatal error: 'xtd/drawing/color.h' file not found`

# To Reproduce

1. cd xtd
2. mkdir build
3. cd build
4. cmake -DXTD_BUILD_LIBRARIES_XTD_DRAWING=OFF -DXTD_BUILD_LIBRARIES_XTD_FORM=OFF -DXTD_BUILD_LIBRARIES_XTD_TUNIT=OFF ..
5. make

# Expected behaviour

The project is successfully built

# Desktop (please complete the following information)

 - OS: macOS
 - Version: 13.3.1 
- xtd version: master (83f33454e496755076d13442ef9a2fe3323e7830)

**Comment by gammasoft71** [comment]
Thank you for your feedback😉.

I am not available for 15 days.
I will look as soon as possible.

Regards,
Gammasoft

**Comment by gammasoft71** [comment]
Hi,

I tried to correct the problem.
Unfortunately I do not have a computer to validate it here.
Could you try for me and tell me if the build works.

Thanks in advance.
Gammasoft

**Comment by ex-purple** [comment]
Unfortunately I can't check it now too 😁

You may also be interested that  I tied append [xtd port](https://github.com/microsoft/vcpkg/pull/31857) for the vcpkg. But I have compilation problem in CI, although everything is builds locally.

**Comment by gammasoft71** [comment]
😀, no worries, I'll test later. 

Regarding vcpkg, yes I'm interested see issue #221. If I can help you don’t hesitate to ask me.

Thank you for your participation in fiare advance xtd.

**Comment by ex-purple** [comment]
About vcpkg
please check the error from https://dev.azure.com/vcpkg/public/_build/results?buildId=90352&view=artifacts&pathAsName=false&type=publishedArtifacts.

**Comment by gammasoft71** [comment]
I can't open logs from my iPad. Something is wrong. 🤨
I will watch from a computer as soon as possible (not before 15 days).

**Comment by gammasoft71** [comment]
still can't open the logs from my computer. Something is wrong. 🤨
Can you send me the log file. Thank you very much.

For the next exchange on VCPK can you write with the dedicated #221 issue.
Because this issue only concerns the XTD_BUILD_LIBRARIES_XTD_DRAWING=OFF option.

**Comment by gammasoft71** [comment]
This is fixed now with the commmit https://github.com/gammasoft71/xtd/commit/97bbdce5b03587e8078387c882c58d664d1ce1b2. If you set  XTD_BUILD_LIBRARIES_XTD_DRAWING option to OFF the project build correctly.
