### ISSUE TITLE
[FEATURE] Adding Lua binding

### ISSUE THREAD

**Issue by iahung2** [gammasoft71/xtd#233]
Lua is a good alternative to Python. The IUP library provides Lua support out of the box:

https://www.tecgraf.puc-rio.br/iup/

**Comment by gammasoft71** [comment]
Hi again,

It's a good idea, of course. It would be nice to have a binding of xtd in C, Python and LUA.

I started creating the [xtd_c](https://github.com/gammasoft71/xtd_c) project, which is a C binding of xtd. Unsurprisingly, it works very well.
But this project requires an enormous amount of time to get up and running.

The same applies to the other bingings (Python and LUA).
These two bindings need to be created as xtd_c in a separate project (xtd_python and xtd_lua for example).

But unfortunately for the moment xtd is far from being in a state of maintenance which would allow me to have time to devote to the various binding.
Here's a look at the various [developments remaining](https://gammasoft71.github.io/xtd/docs/documentation/roadmap) in xtd.
If I disperse myself on other projects, development of xtd will be delayed.

However, if there's a volunteer to take on the project, I'm obviously ready to give as much information as possible to help.
