### ISSUE TITLE
[BUG] xtdc-gui.exe not found

### ISSUE THREAD

**Issue by Dawid-Witkowski** [gammasoft71/xtd#245]
# Describe the bug
after downloading the xtd from [this page](https://gammasoft71.github.io/xtd/docs/downloads), extracting the directory from the zip file, opening cmd as an administrator, navigating to the xtd-0.1.1-beta directory and running `install` it seems to crash at the end with:
```
'#set' is not recognized as an internal or external command,
operable program or batch file.

SUCCESS: Specified value was saved.
launch xtdc-gui...
The system cannot find the file C:\Program Files (x86)\xtd\bin\xtdc-gui.exe.
```
The system cannot find the file C:\Program Files (x86)\xtd\bin\xtdc-gui.exe.

# Expected behaviour
Launching the gui app

# Screenshots
![image](https://github.com/gammasoft71/xtd/assets/98784426/3aa232aa-3efe-469d-a978-abe14a3c927c)

# Desktop (please complete the following information)

 - OS: Windows
 - Version: 10
- xtd version: xtd-0.1.1-beta
- cmake version: 3.28.1 (can run `cmake --version` from the cmd)

**Comment by Dawid-Witkowski** [comment]
Also, just to clarify, I did follow the steps in https://gammasoft71.github.io/xtd/docs/downloads#windows-10-or-later, but to no avail

**Comment by gammasoft71** [comment]
Hi,

First of all, thank you for your interest in xtd 😉 .

Can you manually check if the directory `C:\Program Files (x86)\bin` exists and contains the xtd executable files.
* If so, check your user's `path` environment variable and see if it contains the path `C:\Program Files (x86)\xtd\bin` if not, add it.
* If not, are you sure you're running your "Command Prompt" as an administrator? If you are not an administrator, xtd cannot be installed in the directory `C:\Program Files (x86)\`. If you were an administrator but xtd didn't install, could you send me the full console output? If you've lost it, you can reinstall xtd after deleting the `build` directory in the` xtd` directory.

**Comment by Dawid-Witkowski** [comment]
The directory `C:\Program Files (x86)\bin` does not exist in my case and I am running the script as an administrator, will edit this post and include the full console output once it crashes again😄

**Comment by Dawid-Witkowski** [comment]
Couldn't include the entire stacktrace in the post itself (body too long), so I decided to post it as a [pastebin](https://pastebin.com/1UJ5Tz7C)

**Comment by Dawid-Witkowski** [comment]
the OS version seems to be in the pastebin: `Microsoft Windows [Version 10.0.19045.3930]` (Win 10)
Visual Studio:
```
Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.5
```

**Comment by gammasoft71** [comment]
There is a build error on control_list.h with std::sort , the header `algorithm ` is missing... Sorry  my bad.
I will create a new release v0.1.2 as soon as possible. 

Four solutions are available:

## Patch your sources

Updates `your_xtd_path/src/xtd.forms/include/xtd/forms/list_control.h` file with `#include <algorithm>` on line 6.

## Use v0.1.0-beta branch

The correction is present see commit :  https://github.com/gammasoft71/xtd/commit/311b2c2b91e4fe870665a7c9570371fb78f29732

```bash
git clone --branch v0.1.0-beta  https://github.com/gammasoft71/xtd.git
install
```

## Use latest xtd version

```bash
git clone  https://github.com/gammasoft71/xtd.git
install
```

## Wait the v0.1.2-beta release

Wait until I release version v0.1.2-beta.

**Comment by Dawid-Witkowski** [comment]
will try to run `install` after pulling from the branch, will keep you posted (hopefully the next comment will close this issue)

**Comment by Dawid-Witkowski** [comment]
![image](https://github.com/gammasoft71/xtd/assets/98784426/0b5dba11-9d78-429f-82b6-59935c464c9b)
![image](https://github.com/gammasoft71/xtd/assets/98784426/d15cdca0-7d22-4ccd-825b-79454fe7eaa4)

Well, it seems that it has worked, thank you ❤️
