### ISSUE TITLE
[QUESTION] Code autosuggestion (IntelliSense) in VS2022

### ISSUE THREAD

**Issue by Dawid-Witkowski** [gammasoft71/xtd#246]
# Your question

Hello, me again, 
I'm having trouble implementing code autosuggestion in VS2022, the problem seems to be related to this picture:
![image](https://github.com/gammasoft71/xtd/assets/98784426/a0b577f7-3221-4bd6-ae38-7d2b31dd683d)

Is there any docs page that covers how to add that? is that an existing feature?

(Cmake rookie, so forgive me :D)
cheers!

**Comment by gammasoft71** [comment]
Hi again,

Before trying your first application, have you tried building an xtd example. You can open it from xtdc-gui. If the example builds and runs. Check your CMakeList.txt file. You can send it to me and I can help if I see something wrong.

**Comment by Dawid-Witkowski** [comment]
CMakeList.txt:
```
cmake_minimum_required(VERSION 3.3)
Project(form1)
find_package(xtd REQUIRED)
add_sources(form1.cpp)
target_type(GUI_APPLICATION)
```

**Comment by Dawid-Witkowski** [comment]
Yes, didn't help

**Comment by gammasoft71** [comment]
If the example builds and runs, that means the xtd build chain is correct 😉.

Are you correctly generating your solution with the `xtdc` or `cmake` tools?

## With `xtdc`command

To build this project, open "Terminal" and type following lines:

```shell
cd your_project
xtdc generate
xtdc open
```
Select `your_project` project and type Ctrl+F5 to build and run it.

## With `cmake` command

To build this project, open "Terminal" and type following lines:

```shell
cd your_project
mkdir build && cd build
cmake ..
start your_project.sln
```
Select `your_project` project and type Ctrl+F5 to build and run it.

## With `xtdc-gui`applicarion

Launch `xtdc-gui` 
Click "Open a project or solution" button
Select `your_project`directory
When Visual Studio is started, select `your_project` project and type Ctrl+F5 to build and run it.

## With `CMake`gui applicarion

Launch `CMake` 
Click "Browse Sources..." button
Select `your_project`directory
Click "Browse Build..." button
Select `your_project\build`directory
Click "Configure" button
Click "Generate" button
Click "Open Project" button
When Visual Studio is started, select `your_project` project and type Ctrl+F5 to build and run it.

**Comment by gammasoft71** [comment]
Sorry for the previous answer, I didn't factor in the fact that you were using VS Code. 

I've never used VS Code for a CMake project.

Make sure you have installed the CMake plugin and that it is properly configured.

**Comment by gammasoft71** [comment]
Hi again,

I'm installing Visual Studio Code on my Windows 11 and I can run an example from it.

## Workflow

* Install [Visual Studio Code](https://code.visualstudio.com/)
* Install the following extensions :
  *[C++ extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)
  * [CMake Tools extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cmake-tools)
* Open the command palette (Shift+Ctrl+P )
* Type `CMake: Quick Start`
* Select the compiler (in my case Visual Studio Community 2022 Release - arm64.
* Open the command palette (Shift+Ctrl+P )
* Type `CMake: Build`
* In the CMake panel set Debug and Launch target
* Click Launch `Ruin terminal` button.

For more information see [Get started with CMake Tools on Linux](https://code.visualstudio.com/docs/cpp/cmake-linux). It also works on Windows.

I hope this helps. 😉

**Comment by Dawid-Witkowski** [comment]
Might've confused VS2022 and VS code, will try the tips out later today, thank you for the quick response :)
