### ISSUE TITLE
[BUG]  fatal error: alsa/asoundlib.h: No such file or directory

### ISSUE THREAD

**Issue by grantrostig** [gammasoft71/xtd#248]
Got error as below on ./install. Not sure if the huge output from the script is stored anywhere, I provided at least one fatal error that did not halt the script.  
uname -a
Linux fx6350-fedora 6.6.13-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Jan 20 18:03:28 UTC 2024 x86_64 GNU/Linux

After the error, you can see that I installed alsa.  Should I just re-run the install, or delete something first?

Thanks in advance for any assistance.
+++++++++++++++++++++++
[ 26%] Building CXX object src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/src/xtd/native/linux/console.cpp.o
[ 26%] Building CXX object src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/src/xtd/native/linux/debugger.cpp.o
/home/grostig/src/Worthy-OS/xtd/src/xtd.core.native.linux/src/xtd/native/linux/console.cpp:17:10: fatal error: alsa/asoundlib.h: No such file or directory
   17 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/build.make:90: src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/src/xtd/native/linux/console.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:541: src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
[  0%] Built target xtd.core.native
[ 25%] Built target xtd.core
[ 25%] Building CXX object src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/src/xtd/native/linux/console.cpp.o
/home/grostig/src/Worthy-OS/xtd/src/xtd.core.native.linux/src/xtd/native/linux/console.cpp:17:10: fatal error: alsa/asoundlib.h: No such file or directory
   17 | #include <alsa/asoundlib.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/build.make:90: src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/src/xtd/native/linux/console.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:541: src/xtd.core.native.linux/CMakeFiles/xtd.core.native.linux.dir/all] Error 2
gmake: *** [Makefile:166: all] Error 2
~/src/Worthy-OS/xtd/build ~/src/Worthy-OS/xtd
~/src/Worthy-OS/xtd
cp: cannot create regular file '/usr/local/share/xtd/wxwidgets_release_install_manifest.txt': No such file or directory
cp: cannot create regular file '/usr/local/share/xtd/wxwidgets_debug_install_manifest.txt': No such file or directory
cp: cannot stat 'build/Release/install_manifest.txt': No such file or directory
cp: cannot stat 'build/Debug/install_manifest.txt': No such file or directory
Launching xtdc-gui...
grostig@fx6350-fedora:~/src/Worthy-OS/xtd$ 
grostig@fx6350-fedora:~/src/Worthy-OS/xtd$ 
grostig@fx6350-fedora:~/src/Worthy-OS/xtd$ 
grostig@fx6350-fedora:~/src/Worthy-OS/xtd$ sudo dnf install alsa-lib-devel
Installing:
 alsa-lib-devel                                                                 x86_64                                                                 1.2.11-2.fc39                                                                    updates                                                                 901 k
`

**Comment by gammasoft71** [comment]
First of all, thank you for your interest in xtd.

For your information, unfortunately, the installation result is not saved anywhere.

Before reinstalling, you need to delete the `build` folder.

I hope this helps.

**Comment by grantrostig** [comment]
Thank you for your quick response.  I'm very impressed by the project and the documentation.

I have also installed these for Fedora 39 and the build almost worked:
alsa-lib-devel
gsound-devel
libuuid-devel

I still have these errors, but the gui did start.  Do you know if I need these two files?
+++++++++++++++++++++++++++++++++++++
-- Up-to-date: /usr/local/share/xtd/locale/zh_TW/version.strings
~/src/Worthy-OS/xtd/build ~/src/Worthy-OS/xtd
~/src/Worthy-OS/xtd
cp: cannot stat 'build/3rdparty/wxwidgets/build_cmake/Release/install_manifest.txt': No such file or directory
cp: cannot stat 'build/3rdparty/wxwidgets/build_cmake/Debug/install_manifest.txt': No such file or directory

**Comment by gammasoft71** [comment]
These two files are not always necessary and in your case they don't exist. 
I'm going to add a check on the existence of the files so as not to launch a copy that will fail. ;-)

**Comment by gammasoft71** [comment]
Fixed in the commit  [07b1b3e](https://github.com/gammasoft71/xtd/commit/07b1b3ecb7bc4a15f2c249c260c7526bf1c7e9fb)

**Comment by gammasoft71** [comment]
The result of the installation is now recorded in the build/install.log file. 
See commit [fe6d500](https://github.com/gammasoft71/xtd/commit/fe6d500c9223c4af1232c836b987a88b3a38f3b2) and commit [b4fafaf](https://github.com/gammasoft71/xtd/commit/b4fafaf39d8aae91e2a28a60a1087e7f6db5b8be).

**Comment by grantrostig** [comment]
Thanks for your quick action.

You may also want to consider adding the following packages to the fedora yum install list.  They seemed to be what allowed my install to work on Fedora39.
alsa-lib-devel
gsound-devel
libuuid-devel

**Comment by gammasoft71** [comment]
Hello again,

thank you for your involvement.

Yes, you are right, these packages are mandatory for xtd.

But I'm surprised because the installation procedure includes these packages except `libuuid-deve` which I forgot 😅.

The following line corresponds to the installation of packages for the `Fedora` distribution:

```bash
sudo yum update; sudo yum install alsa-lib-devel cmake gtk3-devel gsound-devel gtk3-devel -y;;
```

Can you confirm that these packages have not been installed by the xtd installer?

Otherwise I'll have to investigate...

**Comment by gammasoft71** [comment]
The `libuuid-devel` is added for, CentOs, Fedora and RedHat, see commit [029a969](https://github.com/gammasoft71/xtd/commit/029a9691618c7da7310b035c9e2c0f0b9190f2f3).
