### ISSUE TITLE
[BUG] xtd does not install at all

### ISSUE THREAD

**Issue by defiantnerd** [gammasoft71/xtd#254]
# Describe the bug

Following the instructions of the readme, on Windows it just fails at a very early stage

# To Reproduce

1. use `git clone https://github.com/gammasoft71/xtd.git`
2. `cd xtd`
3. .`\install.cmd`
4. See error: 
```
Install xtd libraries version 0.2.0, copyright ┬® 2024 Gammasoft
Das System kann den angegebenen Pfad nicht finden.
        0 Datei(en) verschoben.
```

# Expected behaviour

install something or at least do something.

# Screenshots

terminal with just the message above

# Desktop (please complete the following information)

 - OS: Windows 11
 - Version: 23H2 (Build 22631.3810)
- xtd version: 0.2.0

German system language

**Workaround**

none

**Comment by gammasoft71** [comment]
First of all, thank you for your interest in xtd.

Indeed, there is a problem when installing xtd on Windows. I recently added the ability to save the installation process using a special tee.cmd command. Unfortunately, this command doesn't work as expected. I have temporarily removed this option until it works properly.

The second problem is that in the documentation I forgot to specify that the command prompt must be run in "administrator" mode. This has now been corrected.
