### ISSUE TITLE
[BUG] build error on FreeBSD

### ISSUE THREAD

**Issue by Curculigo** [gammasoft71/xtd#256]
# Describe the bug

* xtd has build errors on FreeBSD :

```
/work/xtd/src/xtd.core.native.unix/src/xtd/native/unix/../../../../include/xtd/native/unix/semaphore.h:16:17: error: use of undeclared identifier 'CLOCK_REALTIME'
   16 |   clock_gettime(CLOCK_REALTIME, &timeout);
```

```
/work/xtd/src/xtd.core.native.unix/src/xtd/native/unix/memory.cpp:42:48: error: use of undeclared identifier '_SC_AVPHYS_PAGES'
   42 |   return get_total_physical_memory() - sysconf(_SC_AVPHYS_PAGES) * sysconf(_SC_PAGE_SIZE);
```

# Expected behaviour

build with no error.

**Comment by gammasoft71** [comment]
Hi, 

First of all thank you for your interest in xtd.

I've updated the xtd trunk to try and fix the build on FreeBSD :
* [Fix include file](https://github.com/gammasoft71/xtd/commit/684ee7cf4d1c5f283c2ab607ba6cb5dc9ec404b3)
* [Fix include file](https://github.com/gammasoft71/xtd/commit/02c8ebc4af8c3718a4cded55850627c4258a0b88)
* [Fix xtd::native::memory::get_total_physical_memory and xtd::native::memory::get_used_physical_memory methods on FreeBSD](https://github.com/gammasoft71/xtd/commit/52bcecd7f7e44a1c3050f21ed17dbd2875f162bf)

Can you try to check if xtd compiles correctly on FreeBSD now. Thanks.

**Comment by Curculigo** [comment]
```
/work/xtd/src/xtd.core.native.unix/src/xtd/native/unix/memory.cpp:18:46: error: use of undeclared identifier 'HW_MEMSIZE'
   18 |   auto mib = std::array<int32_t, 2> {CTL_HW, HW_MEMSIZE};
      |                                              ^
/work/xtd/src/xtd.core.native.unix/src/xtd/native/unix/memory.cpp:46:46: error: use of undeclared identifier 'VM_FREE_COUNT'
   46 |   auto mib = std::array<int32_t, 2> {CTL_HW, VM_FREE_COUNT};
      |                                              ^
```

**Comment by gammasoft71** [comment]
Sorry for the inconvenience, but it's not easy to find exactly the right `sysctl` parameter definitions on FreeBSD.
Now I've found in the [documentation](https://man.freebsd.org/cgi/man.cgi?sysctlbyname) the `sysctlbyname` method and I think that ([Try to fix build on FreeBSD](https://github.com/gammasoft71/xtd/commit/44f6ec72ec4bf9daad9f19cf3fdda2663546302a)) will solve the problem.

I know Linux and Darwin better. I don't use FreeBSD.

Can you try to check if xtd compiles correctly for you now. Thanks.

**Comment by Curculigo** [comment]
```
In file included from /work/xtd/src/xtd.core.native.unix/src/xtd/native/unix/settings.cpp:2:
In file included from /work/xtd/src/xtd.core.native/include/xtd/native/settings:2:
/work/xtd/src/xtd.core.native/include/xtd/native/settings.h:12:10: fatal error: 'xtd/static.h' file not found
   12 | #include <xtd/static.h>
      |          ^~~~~~~~~~~~~~
```

**Comment by gammasoft71** [comment]
Sorry again, I pushed the fixes into the trunk. 
I created a FreeBSD VM, and the build works.

Unfortunately [Github actions] (https://github.com/gammasoft71/xtd/actions) doesn't allow you to have a FreeBSD IC.
We'll have to see what can be done in the future.

**Comment by gammasoft71** [comment]
You can show [xtdc](https://github.com/gammasoft71/xtd/blob/master/tools/xtdc/README.md) and  [xtdc-gui](https://github.com/gammasoft71/xtd/blob/master/tools/xtdc-gui/README.md) on [FreeBSD](https://www.freebsd.org) 14.1

![FreeBSD - xtdc-gui](https://github.com/user-attachments/assets/0a39bb12-1fb7-4ef7-9b01-96c8b7edec8f)

**Comment by Curculigo** [comment]
`gmake -C build` will install the .desktop files into `.local/share/applications`?
