### ISSUE TITLE
[BUG] Windows installation failure

### ISSUE THREAD

**Issue by hros** [gammasoft71/xtd#257]
# Describe the bug

using the `install` script on the development branch (cloning the repo) in Windows 11 fails

# To Reproduce

1. cd \src
2. git clone https://github.com/gammasoft71/xtd.git
3. cd xtd
4. install (using Administrator cmd window)

# Expected behaviour

successful installation for Visual Studio

# Screenshots
<details>
<summary>output of install</summary>
C:\src\xtd>install
Install xtd libraries version 0.2.0, copyright ┬⌐ 2024 Gammasoft

  Operating System is Windows
"Get cmake_install_prefix..."
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.41.34120.0
-- The CXX compiler identification is MSVC 19.41.34120.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done (3.7s)
-- Generating done (0.0s)
-- Build files have been written to: C:/src/xtd/build/cmake_install_prefix
cmake_install_prefix_base="C:\Program Files (x86)\wxwidgets"
"Checks wxWidgets..."
-- Building for: Visual Studio 17 2022
-- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- The C compiler identification is MSVC 19.41.34120.0
-- The CXX compiler identification is MSVC 19.41.34120.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES wxWidgets_INCLUDE_DIRS) (Required is at least version "3.2.0")
-- Configuring done (3.8s)
-- Generating done (0.0s)
-- Build files have been written to: C:/src/xtd/build/test_wxwidgets

---------------------------------------------------------------

WARNING : wxWidgets is not already installed!

If you continue wxWidgets will be downloaded, built and installed automatically.

---------------------------------------------------------------

Press ENTER to continue or CTRL-C to stop and install wxWidgets manually...
Install wxWidgets version v3.2.2.1...

  Operating System is Windows
Downloading and installing wxwidgets...
Cloning into 'wxWidgets'...
remote: Enumerating objects: 7029, done.
remote: Counting objects: 100% (7029/7029), done.
remote: Compressing objects: 100% (5845/5845), done.
remote: Total 7029 (delta 1943), reused 2926 (delta 1094), pack-reused 0 (from 0)
Receiving objects: 100% (7029/7029), 22.47 MiB | 10.88 MiB/s, done.
Resolving deltas: 100% (1943/1943), done.
Note: switching to 'a812fffda3fe686c94e24bff27e8effd96e4de64'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Updating files: 100% (6685/6685), done.
Submodule '3rdparty/catch' (https://github.com/wxWidgets/Catch.git) registered for path '3rdparty/catch'
Submodule '3rdparty/nanosvg' (https://github.com/wxWidgets/nanosvg) registered for path '3rdparty/nanosvg'
Submodule '3rdparty/pcre' (https://github.com/wxWidgets/pcre) registered for path '3rdparty/pcre'
Submodule 'src/expat' (https://github.com/wxWidgets/libexpat.git) registered for path 'src/expat'
Submodule 'src/jpeg' (https://github.com/wxWidgets/libjpeg-turbo.git) registered for path 'src/jpeg'
Submodule 'src/png' (https://github.com/wxWidgets/libpng.git) registered for path 'src/png'
Submodule 'src/tiff' (https://github.com/wxWidgets/libtiff.git) registered for path 'src/tiff'
Submodule 'src/zlib' (https://github.com/wxWidgets/zlib.git) registered for path 'src/zlib'
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/3rdparty/catch'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/3rdparty/nanosvg'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/3rdparty/pcre'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/src/expat'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/src/jpeg'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/src/png'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/src/tiff'...
Cloning into 'C:/src/xtd/build/3rdparty/wxWidgets/src/zlib'...
Submodule path '3rdparty/catch': checked out '5f5e4cecd1cafc85e109471356dec29e778d2160'
Submodule path '3rdparty/nanosvg': checked out 'ccdb1995134d340a93fb20e3a3d323ccb3838dd0'
Submodule path '3rdparty/pcre': checked out '5b934c2a6770c05ae3e9bc5f63e0ed5da098b08b'
Submodule path 'src/expat': checked out '23b7f47ef6043929b648de53ac04024c4ac7afcb'
Submodule path 'src/jpeg': checked out '852493611506076fd9ad931d35bf1c3cc5b5a9c3'
Submodule path 'src/png': checked out 'd675c669c8250b7da55747c81a5bd01504449e6e'
Submodule path 'src/tiff': checked out 'af035310bddac3e2f58ae0a330bc6ef168e180f1'
Submodule path 'src/zlib': checked out 'a6c8900ecb9da7ac0d2a67467258fd4c1814b780'
The syntax of the command is incorrect.
</details>

# Desktop (please complete the following information)

 - OS: Windows 11
 - Version: 23H2 (build: 22631.4037)
- xtd version: #master

**Additional context**

**Workaround**

Add a workaround if there is one here.

**Comment by gammasoft71** [comment]
First of all, thank you for your interest in xtd.

Yes, you're right, I've corrected the problem (https://github.com/gammasoft71/xtd/commit/eaa58fe0a705f1cfeebcfbd778fb5ef5f5ed931d)

Thank you for your help.
