### ISSUE TITLE
[BUG] ubuntu build failed with -DXTD_BUILD_SHARED_LIBRARIES=ON 

### ISSUE THREAD

**Issue by hahahahbenny** [gammasoft71/xtd#264]
# Describe the bug

when I build the xtd shared library, it  shows Cyclic dependencies error.

# To Reproduce

the build command is 
```  
/usr/local/bin/cmake -DXTD_BUILD_TOOLS=OFF -DXTD_NATIVE_GRAPHIC_TOOLKIT=wxwidgets -DXTD_BUILD_SHARED_LIBRARIES=ON -DXTD_INSTALL_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/home/bennyWU/.xmake/packages/x/xtd/v0.1.2/6f7b1ebf7d16403bb918df2accf2ff72 -DCMAKE_INSTALL_LIBDIR:PATH=lib -G "Unix Makefiles" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_STATIC_LINKER_FLAGS_RELEASE= "-DCMAKE_C_FLAGS_RELEASE= -O3 -DNDEBUG" -DCMAKE_SHARED_LINKER_FLAGS_RELEASE= -DCMAKE_EXE_LINKER_FLAGS_RELEASE= "-DCMAKE_CXX_FLAGS_RELEASE= -O3 -DNDEBUG" /home/bennyWU/.xmake/cache/packages/2409/x/xtd/v0.1.2/source
```

# Screenshots

The error message appears as follows.

>  CMake Error: The inter-target dependency graph contains the following strongly connected component (cycle):
  "xtd.core.native.unix" of type SHARED_LIBRARY
    depends on "xtd.core" (weak)
  "xtd.core" of type SHARED_LIBRARY
    depends on "xtd.core.native.unix" (weak)
At least one of these targets is not a STATIC_LIBRARY.  Cyclic dependencies are allowed only among static libraries.
CMake Generate step failed.  Build files cannot be regenerated correctly.

![image](https://github.com/user-attachments/assets/61181955-d4a5-4d1b-bb08-37ca334f8d19)

the xtd.core CMakeLists.txt 

![image](https://github.com/user-attachments/assets/4d6bd18a-1258-402b-b5f4-bd37e56e72d6)

# Desktop (please complete the following information)

 - OS: Ubuntu 
 - Version: 20.04.6 LTS
- xtd version: 0.1.2

**Comment by gammasoft71** [comment]
First of all, thank you for your interest in xtd.
Indeed you are right. I will see it

**Comment by gammasoft71** [comment]
Hello, can you check if this works for you?
