### ISSUE TITLE
cannot delete recent projects in xtdc-gui

### ISSUE THREAD

**Issue by BaderEddineOuaich** [gammasoft71/xtd#27]
**Describe the bug**
When selecting a recent project in xtdc-gui and pressing the DEL key, it does not delete the item from the list.

**To Reproduce**
1. Launch xtdc-gui
2. Go to Open recent list and choose a project
3. Press DEL keyboard key
4. Nothing will happen

**Expected behaviour**
Expected the recent project item to be deleted from recent projects list.

**Screenshots**
![pl](https://user-images.githubusercontent.com/49657842/139748629-1480ee3d-7784-4d56-a8fc-2aca52db5292.PNG)
I made a new project to test key_down and key_code's value when pressing the DEL key, it looks like it reports the wrong key_code value of F16:
![image](https://user-images.githubusercontent.com/49657842/139749396-d3e29e08-40db-4e23-967e-74246f93e3d9.png)

**Desktop (please complete the following information):**
- OS: Windows x64
- Version: 10
- xtd version: 0.2.0

**Additional context**
When debugging xtdc-gui in Visual Studio, the key_event_args.key_code() value was  `F16 0x0000007F` instead of `DEL 0x0000002E` (as shown in the screenshots above), which prevent the function `delete_from_open_recent_projects` from being called.

**Comment by gammasoft71** [comment]
On Windows only, when "Delete" (DEL) key is down   : wxKeyEvent::GetUnitcoeKey() is not equal to WXK_NONO but contains WXK_DELETE : fix xtd::forms::native::control_handler::convert_to_virtual_key method.

**Comment by gammasoft71** [comment]
fix in commit : https://github.com/gammasoft71/xtd/commit/dc4fea454a2c30736b3a2ec0c66529430483f8d6
