### ISSUE TITLE
Are there any plans to add new components for GridView(DataGridView)?

### ISSUE THREAD

**Issue by kkptm** [gammasoft71/xtd#36]
Are there any plans to add new components for GridView(DataGridView)?

**Comment by gammasoft71** [comment]
Hello,

The data_grid_view is planned for version 0.3.0 beta.

You can find the xtd dev roadmap here : [roadmap.md](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md)

As this project is an open source project and the developers who participate in it do it on their free time, it is difficult to set a date. But you can follow the development progress. We keep the status updated.

Regards,
Gammasoft
