### ISSUE TITLE
[ENHANCEMENT] Is there a provided uninstaller?

### ISSUE THREAD

**Issue by Wallby** [gammasoft71/xtd#37]
Hello, there seems to be no uninstall/uninstall.cmd nor any mention of how to uninstall in the docs. Hence I am hesitant to try out xtd.

**Comment by gammasoft71** [comment]
Indeed, xtd does not have an uninstall command. I will add it as enhancement.

But xtd can be uninstalled manually.

CMake generates a file install_manifest.txt in the build folder (this folder will be created in the root by the installation)

# Remarks:
For the moment xtd uses the wxWidgets toolkit which is automatically installed with xtd. From version 2.0.0 and following xtd will use the native toolkits of each OS.
You will have to uninstall wxWidgets too.

# Procedure

You just have to make a small script that reads the installation files generated by CMake and delete all the files listed.

# list of files install_manifest.txt :

## Windows:

* build/3rdparty/wxwidgets/build_cmake/install_manifest.txt
* build/install_manifest.txt

## linux e tmacOS:

* build/3rdparty/wxwidgets/build_cmake/Debug/install_manifest.txt
* build/3rdparty/wxwidgets/build_cmake/Release/install_manifest.txt
* build/Debug/install_manifest.txt
* build/Release/install_manifest.txt

Regards,
Gammasoft

**Comment by gammasoft71** [comment]
see [unstall](https://github.com/gammasoft71/xtd/blob/master/docs/downloads.md#uninstall) documentation
