### ISSUE TITLE
install.cmd removed items from my windows path

### ISSUE THREAD

**Issue by Wallby** [gammasoft71/xtd#38]
**Describe the bug**
Some entries were removed from user path variable. I managed to figure out what they were by printing `$Env:Path` in the open powershell window were I ran `./install.cmd` from.

One of the folders that was removed is `C:\Users\maart\AppData\Local\Microsoft\WindowsApps;` (I noticed the bug when trying to run winget, which is in this folder).

**To Reproduce**
I am not going to reproduce this bug, but proof that install.cmd caused this is that `$Env:Path` in the powershell window were I ran 
`./install.cmd` still contained the entries that went missing afterwards (I restored them manually, hope that's ok).

**Expected behaviour**
The user path variable isn't destructively altered (perhaps if the path variable would become too long, cancel install.cmd..?, but I don't think that is the case as several entries were removed from the path variable and the # characters removed far exceeded that of the added string `C:\Program Files (x86)\xtd\bin`.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: 19044.1466
- xtd version: [0.1.0-beta](https://github.com/gammasoft71/xtd/releases/tag/v0.1.0-beta)

**Comment by gammasoft71** [comment]
# Update of the environment variable path :

The [setx](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx) command is used to add the "xtd/bin" folder to the path.

The following lines are a part of install.cmd which concerns the modification of the path environment variable:

```batch
set path=%ProgramFiles(x86)%\xtd\bin;%path%
setx path "%path%"
```

# Limitations:

* Unfortunately, if the path is longer than 1024 characters, it will be truncated. See remarks in [setx documentation](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx).

# Possible correction:

* I don't know if there is another way to update the environment variable path in Windows.

* If there is not, I can as you suggest check the size of the path environment variable and if it exceeds 1024 characters, not interrupt the install but simply not update the path and tell the user that he will have to update the path himself.

# Remarks

* The first thing to check is that the path is not already truncated when I read it.
