### ISSUE TITLE
[QUESTION] How to use CSS? 

### ISSUE THREAD

**Issue by DrTheodor** [gammasoft71/xtd#39]
Hello. This gui library looks awesome and I had a question. Is there a way to use CSS to customize widgets?

**Comment by gammasoft71** [comment]
[Development](https://github.com/gammasoft71/xtd/tree/master/src/xtd.forms/include/xtd/forms/style_sheets) and [documentation](https://github.com/gammasoft71/xtd/blob/master/docs/guide_style_sheets_overview.md) are in progress.

You can follow the progress from the [roadmap](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md): style_sheets enhancement and enhancements ending with _renderer. 

The development is spread over two versions: [0.2.0](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md#release-200-release) and [0.3.0](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md#release-300-release). This is a big development.

There will be predefined [style sheets](https://github.com/gammasoft71/xtd/tree/master/themes), but it will be possible to use your own style sheets for the whole application or even control by control.

You can see an example of style sheet for the control button [here](https://github.com/gammasoft71/xtd/blob/master/themes/macos_dark/button.css).

**Comment by gammasoft71** [comment]
You can find [here](https://github.com/gammasoft71/xtd/tree/master/examples/xtd.forms.examples/user_controls/button_with_style_sheet), an example of how to create your own style for a button.

The development is growing...
