### ISSUE TITLE
Problems of installing xtd in Arch linux and distributions that are based on it

### ISSUE THREAD

**Issue by Mamograg17** [gammasoft71/xtd#40]
**The bug**
I have a problems with installing this framework in Arch linux and also the distributions that are based on it, i tried to install it on Manjaro and it fails, and now in Arch linux and it fails also.

**Expected behaviour**
I can use the xtd in Arch linux without any problems

**Desktop:**
 - OS: Arch linux
 - Version: 1/02/2022
 - kernel : 5.16.4
- xtd version: latest version

**Comment by gammasoft71** [comment]
xtd can be installed automatically on the following versions: CentOS 7, Debian 9.7, Elementary OS 5.0, Fedora 29, LinuxMint 19.1, openSUSE Tumbleweed, RedHat 7.5 and Ubuntu 19.04 (or later).

On the other hand Arch linux and thus Manjaro (which is a distribution based on Arch), you have to install the different packages manually. As described in the [install](https://github.com/gammasoft71/xtd/blob/master/docs/downloads.md#other-linux-distribution).

I have never tested xtd on an Arch distribution.

Can you send me a copy of the installation traces to see where the process is blocking?

**Comment by Mamograg17** [comment]
Please try to install xtd on Arch (and the based distributions), it's really disappointed, can i know where i can find installation traces ?

**Comment by gammasoft71** [comment]
xtd must work on Manjaro because another user whose config is below uses xtd without any problem: 

Linux version 5.10.68-1-MANJARO (builduser@fv-az72-509) (gcc (GCC) 11.1.0, GNU ld (GNU Binutils) 2.36.1) #1 SMP PREEMPT Wed Sep 22 12:29:47 UTC 2021

**Comment by gammasoft71** [comment]
The traces is the output console...

**Comment by Mamograg17** [comment]
I tried o install it again and these are the traces...
Link :https://sharetext.me/eckpimnebs

**Comment by gammasoft71** [comment]
I committed a try-fix for warnings with gcc 11.

Can you try again after doing a git checkout of xtd.

And tell me if it works now.

If you have another error, send me your logs.

Thanks ;-)

Gammasoft

**Comment by gammasoft71** [comment]
The action builds with gcc 11 are successful.

**Comment by Mamograg17** [comment]
Done, it's working now, thank you for your time, keep going.

![Screenshot_20220213_202524](https://user-images.githubusercontent.com/77543518/153771476-a1626060-ffa5-490a-9fc6-895c45c977c7.png)
