### ISSUE TITLE
How to implement tray icon?

### ISSUE THREAD

**Issue by inbei** [gammasoft71/xtd#43]
Hello, I'm trying to use xtd now. I wanted to implement tary icon, but I didn't find a suitable implementation.

Look forward to your reply.

**Comment by gammasoft71** [comment]
The xtd::forms::notify_icon object is not yet implemented, but is planned for version 0.2.0 (which is under development); see the [roadmap](https://github.com/gammasoft71/xtd/blob/master/docs/roadmap.md) for more information.

**Comment by gammasoft71** [comment]
Duplicate #81
