### ISSUE TITLE
[QUESTION] Cmake Error install(error installing..)

### ISSUE THREAD

**Issue by mortzaLootTool** [gammasoft71/xtd#44]
hi...i download it from sourceForge and ... but when i start file install(from cmd and with adminstor)i got Error Cmake and other error....
i have git,Vs Studio,Cmake(version 3.23.0-rc3(laset version)) and other reqiued for this.
i really need this lib pls help me in fixing!
ScreenShot:
![Capture](https://user-images.githubusercontent.com/79837660/160247776-063e03fc-0dc5-44df-bede-58dd1236bba3.PNG)
list error in TXT file:
[Error install.txt](https://github.com/gammasoft71/xtd/files/8355829/Error.install.txt)

Operation System:  Windows 10 Home (ver 2004(AND LASSET UPDATE))
Viusal Studio Ver 2022 Community
Cmake version 3.23.0-rc3(laset version)
Help me!

**Comment by gammasoft71** [comment]
when I read the traces, I see an error because the build/3rdparty folder is not empty and contains a different version of CMakeCache.txt. Can you try the installation again after deleting the build folder.

```shell
del /F /S /Q build
install
```
Let me know if you get an error.

**Comment by mortzaLootTool** [comment]
I did it again this time with your commend
but unfortunately he gave the same error again
you said there is a list in the create / 3 rdparty / cmake file folder ..? I do not have such a file! This is probably a mistake ... you can give me the cmake file of the list in this folder, I do not have this
of course, once I went manually and deleted all the contents of the folder and started again, but this time it gave the same error.
It's a very good library, but it's not easy to install! I'm running it again on Ubuntu, maybe it will work there....

**Comment by gammasoft71** [comment]
Can you start the whole procedure again.

1. Create a new folder.
2. Extract the files from xtd-0.1.0-beta.zip into this new folder
3. Open the console in "Admin" mode
4. Move to the new folder containing xtd.
5. Execute the "install" command
6. Send me the traces again.

It should work. xtd has already been installed really many times on Windows.

**Comment by mortzaLootTool** [comment]
I was able to install it!
Thanks for HELP!
but sorry...i have new error this time after install when xtdx-gui start....
![Capture](https://user-images.githubusercontent.com/79837660/160336472-c5c51b6e-f49b-4084-8e5b-a34951eade80.PNG)
i can use lib without gui mode?i only need lib!
screenshot(the installation process was without problem):
![Capture](https://user-images.githubusercontent.com/79837660/160336760-08c94ac4-339b-468b-bc17-b91ee9a4921a.PNG)
Thank you for helping me....

**Comment by gammasoft71** [comment]
You're welcome

xdc-gui is not fundamental. It only serves as a GUI for the xtdc command line. So everything can be done from the command line. 

You can use the xtd framework as you want.

Does the error occur every time xdc-gui is started or did it happen only once after the installation?

**Comment by mortzaLootTool** [comment]
After installing this error occurs every time I open the program (xtdc -Gui)
But the interesting thing is that when I compile the source of console programs (with cmd) the program is successfully compiled and executed...
![Capture](https://user-images.githubusercontent.com/79837660/160546563-344c9d71-7c20-4071-84c1-9b258ffc75fe.PNG)
But regarding the source of forms programs, it gives an error every time it is opened!
![1](https://user-images.githubusercontent.com/79837660/160546895-927e8256-c697-4134-a214-2f9d999ef26b.PNG)
I do not know what to do, it means t
![160336472-c5c51b6e-f49b-4084-8e5b-a34951eade80](https://user-images.githubusercontent.com/79837660/160547103-eab4b81c-fd5a-4660-a53e-8c8d14c142d6.png)
hat only **console programs** run without errors, but form programs come with errors...

**Comment by gammasoft71** [comment]
It seems that CMake can't generate the project. Even the internal test it does to check the build chain doesn't work.

Could you:

* Check the installation of Visual Studio or need to make a "repair" with the "Visual Studio Installer" tool. 
* Check your "path" environment variable (it is possible that the installation of xtd has truncated your path [#38](https://github.com/gammasoft71/xtd/issues/38)). If necessary update your path.
* Redo the compilation test.


For information here is the typical path I use:

```
C:\Windows\system32;
C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Windows\System32\OpenSSH\;
C:\Program Files\Git\cmd;
C;
C:\Users\gammasoft71\AppData\Local\Microsoft\WindowsApps;
C:\Users\gammasoft71\AppData\Local\GitHubDesktop\bin;
C:\Program Files\CMake\bin;
C:\Program Files (x86)\doxygen\bin;
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.31.31103\debug_nonredist\x64\Microsoft.VC143.DebugCRT;
C:\Users\gammasoft71\.dotnet\tools;
C:\Program Files (x86)\xtd\bin
```
